//src/config/env.js
// VALIDATION STRICTE DE L'ENVIRONNEMENT FRONTEND (Fail-Fast)
// STANDARD: Industriel

const ENV = {
  API_URL: process.env.EXPO_PUBLIC_API_URL,
  SENTRY_DSN: process.env.EXPO_PUBLIC_SENTRY_DSN,
  APP_ENV: process.env.EXPO_PUBLIC_APP_ENV || 'development',
  LOCATIONIQ_TOKEN: process.env.EXPO_PUBLIC_LOCATIONIQ_TOKEN,
  FACEBOOK_LINK: process.env.EXPO_PUBLIC_FACEBOOK_LINK,
  
  FIREBASE_API_KEY: process.env.EXPO_PUBLIC_FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN: process.env.EXPO_PUBLIC_FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID: process.env.EXPO_PUBLIC_FIREBASE_PROJECT_ID,
  FIREBASE_STORAGE_BUCKET: process.env.EXPO_PUBLIC_FIREBASE_STORAGE_BUCKET,
  FIREBASE_MESSAGING_SENDER_ID: process.env.EXPO_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID: process.env.EXPO_PUBLIC_FIREBASE_APP_ID,
  FIREBASE_VAPID_KEY: process.env.EXPO_PUBLIC_FIREBASE_VAPID_KEY,
};

if (!ENV.API_URL) {
  console.error("[FATAL ERROR] EXPO_PUBLIC_API_URL est manquant ! L'application ne peut pas communiquer avec le serveur.");
}

export default ENV;